site_name: Documentation hub of the project POLVO in CTRC@ENKI
nav:
  - Home: index.md
  - Sub Page: subpage.md

theme:
  name: material
  font:
    text: Archivo
    code: Fira Code
  palette:
    scheme: default
    primary: indigo
    accent: indigo

plugins:
  - search
  - awesome-nav
  - i18n:
      default_language: en
      languages:
        en: English
        ko: 한국어
      no_translation:
        en: "No translation available"
        ko: "번역이 없습니다"

validation:
  absolute_links: ignore
  unrecognized_links: ignore

nav: