name: CI/CD Build & Deploy MkDocs

# Trigger on pushes to primary branches
on:
  push:
    branches:
      - main
      - master

# Grant write access so mkdocs can push to gh-pages
permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"  
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Deploy via mkdocs gh-deploy
      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force
